version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.23.1

workflows:
  build:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          filters:
            branches:
              only: master
      - orb-tools/publish:
          context: org-context
          orb-ref: arribada/docker@0.0.5
          publish-token-variable: CIRCLECI_API_TOKEN
          checkout: false
          attach-workspace: true
          requires:
            - orb-tools/pack
          filters:
            branches:
              only: master
